### ISSUE TITLE
Detached from head?

### ISSUE THREAD

**Issue by meerestier** [jyruzicka/omniboard#18]
Even after --reset, I get this message.

**Comment by meerestier** [comment]
I get this output, when resetting:

```
Invalid date/time in zip entry
Invalid date/time in zip entry
Invalid date/time in zip entry
Invalid date/time in zip entry
Invalid date/time in zip entry
Invalid date/time in zip entry
Invalid date/time in zip entry
Invalid date/time in zip entry
Invalid date/time in zip entry
Invalid date/time in zip entry
Invalid date/time in zip entry
Invalid date/time in zip entry
Invalid date/time in zip entry
Invalid date/time in zip entry
Invalid date/time in zip entry
Invalid date/time in zip entry
Invalid date/time in zip entry
Invalid date/time in zip entry
Invalid date/time in zip entry
Invalid date/time in zip entry
Invalid date/time in zip entry
Invalid date/time in zip entry
Invalid date/time in zip entry
Invalid date/time in zip entry
Invalid date/time in zip entry
Invalid date/time in zip entry
Invalid date/time in zip entry
/usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/time.rb:254:in `make_time': no time information in "" (ArgumentError)
	from /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/time.rb:366:in `parse'
	from /usr/local/lib/ruby/gems/2.3.0/gems/rubyfocus-0.5.5/lib/rubyfocus/items/task.rb:36:in `block in apply_xml'
	from /usr/local/lib/ruby/gems/2.3.0/gems/rubyfocus-0.5.5/lib/rubyfocus/includes/conditional_exec.rb:4:in `conditional_set'
	from /usr/local/lib/ruby/gems/2.3.0/gems/rubyfocus-0.5.5/lib/rubyfocus/items/task.rb:36:in `apply_xml'
	from /usr/local/lib/ruby/gems/2.3.0/gems/rubyfocus-0.5.5/lib/rubyfocus/items/project.rb:38:in `apply_xml'
	from /usr/local/lib/ruby/gems/2.3.0/gems/rubyfocus-0.5.5/lib/rubyfocus/items/item.rb:18:in `initialize'
	from /usr/local/lib/ruby/gems/2.3.0/gems/rubyfocus-0.5.5/lib/rubyfocus/items/task.rb:23:in `initialize'
	from /usr/local/lib/ruby/gems/2.3.0/gems/rubyfocus-0.5.5/lib/rubyfocus/items/project.rb:33:in `initialize'
	from /usr/local/lib/ruby/gems/2.3.0/gems/rubyfocus-0.5.5/lib/rubyfocus/includes/parser.rb:18:in `new'
	from /usr/local/lib/ruby/gems/2.3.0/gems/rubyfocus-0.5.5/lib/rubyfocus/includes/parser.rb:18:in `parse'
	from /usr/local/lib/ruby/gems/2.3.0/gems/rubyfocus-0.5.5/lib/rubyfocus/document.rb:83:in `block in apply_xml'
	from /usr/local/lib/ruby/gems/2.3.0/gems/rubyfocus-0.5.5/lib/rubyfocus/document.rb:82:in `each'
	from /usr/local/lib/ruby/gems/2.3.0/gems/rubyfocus-0.5.5/lib/rubyfocus/document.rb:82:in `apply_xml'
	from /usr/local/lib/ruby/gems/2.3.0/gems/rubyfocus-0.5.5/lib/rubyfocus/document.rb:39:in `initialize'
	from /usr/local/lib/ruby/gems/2.3.0/gems/omniboard-1.1.1/lib/omniboard/omniboard.rb:111:in `new'
	from /usr/local/lib/ruby/gems/2.3.0/gems/omniboard-1.1.1/lib/omniboard/omniboard.rb:111:in `create_document'
	from /usr/local/lib/ruby/gems/2.3.0/gems/omniboard-1.1.1/bin/omniboard:25:in `<top (required)>'
	from /usr/local/bin/omniboard:23:in `load'
	from /usr/local/bin/omniboard:23:in `<main>'
```

**Comment by jyruzicka** [comment]
Yup, looks like it's erroring when trying to update, which will stop it properly updating to head :).

First things first, have you tried updating rubyfocus? Just running `gem update` should hopefully push us to `0.5.11`, which might fix the issue anyway.

**Comment by meerestier** [comment]
Thank you, updating and then resetting (--reset) did the trick…
