### ISSUE TITLE
[DEPRECATION] This gem has been renamed to optimist and will no longer be supported. Please switch to optimist as soon as possible.

### ISSUE THREAD

**Issue by mikcaldentey** [jyruzicka/omniboard#29]
[DEPRECATION] This gem has been renamed to optimist and will no longer be supported. Please switch to optimist as soon as possible.
/Library/Ruby/Gems/2.3.0/gems/rubyfocus-0.5.15/lib/rubyfocus/fetchers/local_fetcher.rb:16:in `join': no implicit conversion of nil into String (TypeError)
	from /Library/Ruby/Gems/2.3.0/gems/rubyfocus-0.5.15/lib/rubyfocus/fetchers/local_fetcher.rb:16:in `base'
	from /Library/Ruby/Gems/2.3.0/gems/rubyfocus-0.5.15/lib/rubyfocus/document.rb:38:in `initialize'
	from /Library/Ruby/Gems/2.3.0/gems/omniboard-1.2.3/lib/omniboard/omniboard.rb:111:in `new'
	from /Library/Ruby/Gems/2.3.0/gems/omniboard-1.2.3/lib/omniboard/omniboard.rb:111:in `create_document'
	from /Library/Ruby/Gems/2.3.0/gems/omniboard-1.2.3/bin/omniboard:24:in `<top (required)>'
	from /usr/local/bin/omniboard:22:in `load'
	from /usr/local/bin/omniboard:22:in `<main>'

**Comment by jyruzicka** [comment]
Just pushed an updates Gemfile, should fix this (1.2.4).

**Comment by mikcaldentey** [comment]
I don't know if I'm doig something wrong, but it doesnt work. The same error.

thanks.

**Comment by jyruzicka** [comment]
Actual error seems to be coming from rubyfocus. Try updating rubyfocus to the latest version - this should fix the issue (or at least change the error message).

I'll be pushing the requirement for the new version of rubyfocus to this gem as soon as I can.
